import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardContextProvider from "@/providers/DashboardContextProvider";
import DashBoardSideBarWrapper from "@/components/pageSection/layout/DashBoardSideBarWrapper";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Khokon Pharma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-center" />
        <DashboardContextProvider>
          <DashBoardSideBarWrapper> {children}</DashBoardSideBarWrapper>
        </DashboardContextProvider>
      </body>
    </html>
  );
}
